# Generated by Django 4.2.4 on 2023-08-24 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='user_admin',
            field=models.BooleanField(default=False),
        ),
    ]
